// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: emgpacket.proto

package at.fhooe.mc.emg.messaging.model.protobuf;

public final class ProtocolBuffers {
  private ProtocolBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmgPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double channels = 1;</code>
     */
    java.util.List<java.lang.Double> getChannelsList();
    /**
     * <code>repeated double channels = 1;</code>
     */
    int getChannelsCount();
    /**
     * <code>repeated double channels = 1;</code>
     */
    double getChannels(int index);

    /**
     * <code>int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>int32 heartRate = 3;</code>
     */
    int getHeartRate();
  }
  /**
   * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket}
   */
  public  static final class EmgPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket)
      EmgPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EmgPacket.newBuilder() to construct.
    private EmgPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EmgPacket() {
      channels_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
      heartRate_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EmgPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                channels_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              channels_.add(input.readDouble());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                channels_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                channels_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 24: {

              heartRate_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = java.util.Collections.unmodifiableList(channels_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNELS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Double> channels_;
    /**
     * <code>repeated double channels = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated double channels = 1;</code>
     */
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated double channels = 1;</code>
     */
    public double getChannels(int index) {
      return channels_.get(index);
    }
    private int channelsMemoizedSerializedSize = -1;

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int HEARTRATE_FIELD_NUMBER = 3;
    private int heartRate_;
    /**
     * <code>int32 heartRate = 3;</code>
     */
    public int getHeartRate() {
      return heartRate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getChannelsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(channelsMemoizedSerializedSize);
      }
      for (int i = 0; i < channels_.size(); i++) {
        output.writeDoubleNoTag(channels_.get(i));
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (heartRate_ != 0) {
        output.writeInt32(3, heartRate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getChannelsList().size();
        size += dataSize;
        if (!getChannelsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        channelsMemoizedSerializedSize = dataSize;
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (heartRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heartRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket)) {
        return super.equals(obj);
      }
      at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket other = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket) obj;

      boolean result = true;
      result = result && getChannelsList()
          .equals(other.getChannelsList());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (getHeartRate()
          == other.getHeartRate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getChannelsCount() > 0) {
        hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
        hash = (53 * hash) + getChannelsList().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + HEARTRATE_FIELD_NUMBER;
      hash = (53 * hash) + getHeartRate();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket)
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.Builder.class);
      }

      // Construct using at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        channels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;

        heartRate_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket getDefaultInstanceForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.getDefaultInstance();
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket build() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket buildPartial() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket result = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = java.util.Collections.unmodifiableList(channels_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.channels_ = channels_;
        result.timestamp_ = timestamp_;
        result.heartRate_ = heartRate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket) {
          return mergeFrom((at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket other) {
        if (other == at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket.getDefaultInstance()) return this;
        if (!other.channels_.isEmpty()) {
          if (channels_.isEmpty()) {
            channels_ = other.channels_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChannelsIsMutable();
            channels_.addAll(other.channels_);
          }
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getHeartRate() != 0) {
          setHeartRate(other.getHeartRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Double> channels_ = java.util.Collections.emptyList();
      private void ensureChannelsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          channels_ = new java.util.ArrayList<java.lang.Double>(channels_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public java.util.List<java.lang.Double>
          getChannelsList() {
        return java.util.Collections.unmodifiableList(channels_);
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public int getChannelsCount() {
        return channels_.size();
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public double getChannels(int index) {
        return channels_.get(index);
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public Builder setChannels(
          int index, double value) {
        ensureChannelsIsMutable();
        channels_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public Builder addChannels(double value) {
        ensureChannelsIsMutable();
        channels_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureChannelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, channels_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double channels = 1;</code>
       */
      public Builder clearChannels() {
        channels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int heartRate_ ;
      /**
       * <code>int32 heartRate = 3;</code>
       */
      public int getHeartRate() {
        return heartRate_;
      }
      /**
       * <code>int32 heartRate = 3;</code>
       */
      public Builder setHeartRate(int value) {
        
        heartRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 heartRate = 3;</code>
       */
      public Builder clearHeartRate() {
        
        heartRate_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket)
    }

    // @@protoc_insertion_point(class_scope:at.fhooe.mc.emg.messaging.model.protobuf.EmgPacket)
    private static final at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket();
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EmgPacket>
        PARSER = new com.google.protobuf.AbstractParser<EmgPacket>() {
      public EmgPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EmgPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EmgPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EmgPacket> getParserForType() {
      return PARSER;
    }

    public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.EmgPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage}
   */
  public  static final class ServerMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage)
      ServerMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerMessage.newBuilder() to construct.
    private ServerMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerMessage() {
      type_ = 0;
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage)) {
        return super.equals(obj);
      }
      at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage other = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage)
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.Builder.class);
      }

      // Construct using at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        data_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage getDefaultInstanceForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.getDefaultInstance();
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage build() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage buildPartial() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage result = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage(this);
        result.type_ = type_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage) {
          return mergeFrom((at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage other) {
        if (other == at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage)
    }

    // @@protoc_insertion_point(class_scope:at.fhooe.mc.emg.messaging.model.protobuf.ServerMessage)
    private static final at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage();
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerMessage>
        PARSER = new com.google.protobuf.AbstractParser<ServerMessage>() {
      public ServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerMessage> getParserForType() {
      return PARSER;
    }

    public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.ServerMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FrequencyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 delay = 1;</code>
     */
    int getDelay();
  }
  /**
   * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage}
   */
  public  static final class FrequencyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage)
      FrequencyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FrequencyMessage.newBuilder() to construct.
    private FrequencyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FrequencyMessage() {
      delay_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FrequencyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              delay_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.Builder.class);
    }

    public static final int DELAY_FIELD_NUMBER = 1;
    private int delay_;
    /**
     * <code>int32 delay = 1;</code>
     */
    public int getDelay() {
      return delay_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (delay_ != 0) {
        output.writeInt32(1, delay_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (delay_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, delay_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage)) {
        return super.equals(obj);
      }
      at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage other = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage) obj;

      boolean result = true;
      result = result && (getDelay()
          == other.getDelay());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DELAY_FIELD_NUMBER;
      hash = (53 * hash) + getDelay();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage)
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.class, at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.Builder.class);
      }

      // Construct using at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        delay_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage getDefaultInstanceForType() {
        return at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.getDefaultInstance();
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage build() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage buildPartial() {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage result = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage(this);
        result.delay_ = delay_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage) {
          return mergeFrom((at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage other) {
        if (other == at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage.getDefaultInstance()) return this;
        if (other.getDelay() != 0) {
          setDelay(other.getDelay());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int delay_ ;
      /**
       * <code>int32 delay = 1;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>int32 delay = 1;</code>
       */
      public Builder setDelay(int value) {
        
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 delay = 1;</code>
       */
      public Builder clearDelay() {
        
        delay_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage)
    }

    // @@protoc_insertion_point(class_scope:at.fhooe.mc.emg.messaging.model.protobuf.FrequencyMessage)
    private static final at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage();
    }

    public static at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FrequencyMessage>
        PARSER = new com.google.protobuf.AbstractParser<FrequencyMessage>() {
      public FrequencyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FrequencyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FrequencyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FrequencyMessage> getParserForType() {
      return PARSER;
    }

    public at.fhooe.mc.emg.messaging.model.protobuf.ProtocolBuffers.FrequencyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017emgpacket.proto\022(at.fhooe.mc.emg.messa" +
      "ging.model.protobuf\"C\n\tEmgPacket\022\020\n\010chan" +
      "nels\030\001 \003(\001\022\021\n\ttimestamp\030\002 \001(\003\022\021\n\theartRa" +
      "te\030\003 \001(\005\"+\n\rServerMessage\022\014\n\004type\030\001 \001(\005\022" +
      "\014\n\004data\030\002 \001(\t\"!\n\020FrequencyMessage\022\r\n\005del" +
      "ay\030\001 \001(\005B;\n(at.fhooe.mc.emg.messaging.mo" +
      "del.protobufB\017ProtocolBuffersb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_at_fhooe_mc_emg_messaging_model_protobuf_EmgPacket_descriptor,
        new java.lang.String[] { "Channels", "Timestamp", "HeartRate", });
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_at_fhooe_mc_emg_messaging_model_protobuf_ServerMessage_descriptor,
        new java.lang.String[] { "Type", "Data", });
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_at_fhooe_mc_emg_messaging_model_protobuf_FrequencyMessage_descriptor,
        new java.lang.String[] { "Delay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
